### ISSUE TITLE
subnets in reference set?

### ISSUE THREAD

**Issue by istvanSA** [SecurityNik/QRadar---Threat-Intelligence-On-The-Cheap#1]
There are a few of the list you use that use subnets , but those cant be put into an reference set? how do you handle that?

**Comment by SecurityNik** [comment]
Good catch! At that time, I assumed I could have handled the subnet. However, my understanding is that QRadar doesn't. I started rewriting the scripting leveraging the REST API. However, I just have not found the time to complete it. Once I do, these things will be fixed.

Thanks for using it.

Do you have any suggestions for how I can improve the script?
